FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -t xenial --assume-yes --no-install-recommends \
    libarchive-dev:armhf \
    libicu-dev:armhf \
    nettle-dev:armhf \
    libacl1-dev:armhf \
    liblzma-dev:armhf \
    libzstd-dev:armhf \
    liblz4-dev:armhf \
    libbz2-dev:armhf \
    zlib1g-dev:armhf \
    libxml2-dev:armhf

COPY openssl-1.1.sh /
RUN /openssl-1.1.sh linux-armv4 arm-linux-gnueabihf-

ENV PKG_CONFIG_ALLOW_CROSS 1
ENV PKG_CONFIG_PATH /usr/lib/arm-linux-gnueabihf/pkgconfig/

# OpenSSL linking
ENV OPENSSL_STATIC=1 \
    OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib

# Set the locale
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
