FROM ubuntu:12.04

COPY common.sh /
RUN WITHOUT_PORTS=yes /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

RUN apt-get install --assume-yes --no-install-recommends \
    g++-multilib qemu

COPY dropbear.sh /
RUN /dropbear.sh

COPY linux-image.sh /
RUN FORCE_STRETCH=yes /linux-image.sh i686

COPY linux-runner /

ENV CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner i686"
