FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -t xenial --assume-yes --no-install-recommends \
    libarchive-dev:armhf

ENV PKG_CONFIG_ALLOW_CROSS 1
ENV PKG_CONFIG_PATH /usr/lib/arm-linux-gnueabihf/pkgconfig/

# Set the locale
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
